ayush = set()
print(ayush)
ayush.add(1)
ayush.add(2)
ayush.add(2)
ayush.add(3)
print(ayush)
ayush.remove(2)
print(ayush)
ayush.add((1,2,3,4,5))
print(ayush)
print(len(ayush))
ayush.clear()
print(ayush)
print(len(ayush))